import random as _random

FAMOUS_MATCHES = [
    {
        "id": "cl_final_2019",
        "competition": "UEFA Champions League Final",
        "date": "1 June 2019",
        "venue": "Wanda Metropolitano, Madrid",
        "home": {
            "name": "Liverpool FC",
            "colour_primary": "#dc2626",
            "colour_secondary": "#7f1d1d",
            "xi": [
                {"name": "Alisson Becker",        "guess_name": "Alisson",    "jersey": 1,  "row": "gk",  "position": "Goalkeeper"},
                {"name": "Trent Alexander-Arnold", "guess_name": "Arnold",     "jersey": 66, "row": "def", "position": "Defender"},
                {"name": "Joel Matip",                                          "jersey": 32, "row": "def", "position": "Defender"},
                {"name": "Virgil van Dijk",        "guess_name": "Van Dijk",   "jersey": 4,  "row": "def", "position": "Defender"},
                {"name": "Andy Robertson",                                      "jersey": 26, "row": "def", "position": "Defender"},
                {"name": "Fabinho",                                             "jersey": 3,  "row": "mid", "position": "Midfielder"},
                {"name": "Jordan Henderson",                                    "jersey": 14, "row": "mid", "position": "Midfielder"},
                {"name": "Georginio Wijnaldum",                                 "jersey": 5,  "row": "mid", "position": "Midfielder"},
                {"name": "Mohamed Salah",                                       "jersey": 11, "row": "fwd", "position": "Forward"},
                {"name": "Roberto Firmino",                                     "jersey": 9,  "row": "fwd", "position": "Forward"},
                {"name": "Sadio Mané",                                          "jersey": 10, "row": "fwd", "position": "Forward"},
            ],
        },
        "away": {
            "name": "Tottenham Hotspur",
            "colour_primary": "#334155",
            "colour_secondary": "#1e293b",
            "xi": [
                {"name": "Hugo Lloris",        "jersey": 1,  "row": "gk",  "position": "Goalkeeper"},
                {"name": "Kieran Trippier",    "jersey": 2,  "row": "def", "position": "Defender"},
                {"name": "Toby Alderweireld",  "jersey": 4,  "row": "def", "position": "Defender"},
                {"name": "Jan Vertonghen",     "jersey": 5,  "row": "def", "position": "Defender"},
                {"name": "Danny Rose",         "jersey": 3,  "row": "def", "position": "Defender"},
                {"name": "Victor Wanyama",     "jersey": 8,  "row": "mid", "position": "Midfielder"},
                {"name": "Moussa Sissoko",     "jersey": 17, "row": "mid", "position": "Midfielder"},
                {"name": "Christian Eriksen",  "jersey": 23, "row": "mid", "position": "Midfielder"},
                {"name": "Dele Alli",          "jersey": 20, "row": "mid", "position": "Midfielder"},
                {"name": "Son Heung-min",      "guess_name": "Son",  "jersey": 7,  "row": "fwd", "position": "Forward"},
                {"name": "Harry Kane",         "jersey": 10, "row": "fwd", "position": "Forward"},
            ],
        },
    },
    {
        "id": "wc_final_2018",
        "competition": "FIFA World Cup Final",
        "date": "15 July 2018",
        "venue": "Luzhniki Stadium, Moscow",
        "home": {
            "name": "France",
            "colour_primary": "#1d4ed8",
            "colour_secondary": "#dc2626",
            "xi": [
                {"name": "Hugo Lloris",          "jersey": 1,  "row": "gk",  "position": "Goalkeeper"},
                {"name": "Benjamin Pavard",       "jersey": 2,  "row": "def", "position": "Defender"},
                {"name": "Raphaël Varane",        "guess_name": "Varane",     "jersey": 4,  "row": "def", "position": "Defender"},
                {"name": "Samuel Umtiti",         "jersey": 5,  "row": "def", "position": "Defender"},
                {"name": "Lucas Hernández",       "guess_name": "Hernandez",  "jersey": 21, "row": "def", "position": "Defender"},
                {"name": "N'Golo Kanté",          "guess_name": "Kante",      "jersey": 13, "row": "mid", "position": "Midfielder"},
                {"name": "Paul Pogba",            "jersey": 6,  "row": "mid", "position": "Midfielder"},
                {"name": "Blaise Matuidi",        "jersey": 14, "row": "mid", "position": "Midfielder"},
                {"name": "Kylian Mbappé",         "guess_name": "Mbappe",     "jersey": 10, "row": "fwd", "position": "Forward"},
                {"name": "Antoine Griezmann",     "jersey": 7,  "row": "fwd", "position": "Forward"},
                {"name": "Olivier Giroud",        "jersey": 9,  "row": "fwd", "position": "Forward"},
            ],
        },
        "away": {
            "name": "Croatia",
            "colour_primary": "#dc2626",
            "colour_secondary": "#f1f5f9",
            "xi": [
                {"name": "Danijel Subašić",      "guess_name": "Subasic",    "jersey": 23, "row": "gk",  "position": "Goalkeeper"},
                {"name": "Šime Vrsaljko",        "guess_name": "Vrsaljko",   "jersey": 2,  "row": "def", "position": "Defender"},
                {"name": "Dejan Lovren",          "jersey": 6,  "row": "def", "position": "Defender"},
                {"name": "Domagoj Vida",          "jersey": 21, "row": "def", "position": "Defender"},
                {"name": "Ivan Strinić",          "guess_name": "Strinic",    "jersey": 3,  "row": "def", "position": "Defender"},
                {"name": "Ivan Rakitić",          "guess_name": "Rakitic",    "jersey": 7,  "row": "mid", "position": "Midfielder"},
                {"name": "Luka Modrić",           "guess_name": "Modric",     "jersey": 10, "row": "mid", "position": "Midfielder"},
                {"name": "Marcelo Brozović",      "guess_name": "Brozovic",   "jersey": 11, "row": "mid", "position": "Midfielder"},
                {"name": "Ivan Perišić",          "guess_name": "Perisic",    "jersey": 4,  "row": "fwd", "position": "Forward"},
                {"name": "Mario Mandžukić",       "guess_name": "Mandzukic",  "jersey": 17, "row": "fwd", "position": "Forward"},
                {"name": "Ante Rebić",            "guess_name": "Rebic",      "jersey": 18, "row": "fwd", "position": "Forward"},
            ],
        },
    },
    {
        "id": "euro_2020_final",
        "competition": "UEFA Euro 2020 Final",
        "date": "11 July 2021",
        "venue": "Wembley Stadium, London",
        "home": {
            "name": "Italy",
            "colour_primary": "#1d4ed8",
            "colour_secondary": "#1e3a8a",
            "xi": [
                {"name": "Gianluigi Donnarumma", "guess_name": "Donnarumma", "jersey": 1,  "row": "gk",  "position": "Goalkeeper"},
                {"name": "Giovanni Di Lorenzo",  "guess_name": "Di Lorenzo", "jersey": 2,  "row": "def", "position": "Defender"},
                {"name": "Leonardo Bonucci",      "jersey": 19, "row": "def", "position": "Defender"},
                {"name": "Giorgio Chiellini",     "jersey": 3,  "row": "def", "position": "Defender"},
                {"name": "Emerson Palmieri",     "guess_name": "Emerson",    "jersey": 24, "row": "def", "position": "Defender"},
                {"name": "Nicolò Barella",       "guess_name": "Barella",    "jersey": 18, "row": "mid", "position": "Midfielder"},
                {"name": "Jorginho",              "jersey": 8,  "row": "mid", "position": "Midfielder"},
                {"name": "Marco Verratti",        "jersey": 6,  "row": "mid", "position": "Midfielder"},
                {"name": "Federico Chiesa",       "jersey": 14, "row": "fwd", "position": "Forward"},
                {"name": "Ciro Immobile",         "jersey": 17, "row": "fwd", "position": "Forward"},
                {"name": "Lorenzo Insigne",       "jersey": 10, "row": "fwd", "position": "Forward"},
            ],
        },
        "away": {
            "name": "England",
            "colour_primary": "#f1f5f9",
            "colour_secondary": "#dc2626",
            "xi": [
                {"name": "Jordan Pickford",   "jersey": 1,  "row": "gk",  "position": "Goalkeeper"},
                {"name": "Kieran Trippier",   "jersey": 12, "row": "def", "position": "Defender"},
                {"name": "John Stones",       "jersey": 5,  "row": "def", "position": "Defender"},
                {"name": "Harry Maguire",     "jersey": 6,  "row": "def", "position": "Defender"},
                {"name": "Luke Shaw",         "jersey": 3,  "row": "def", "position": "Defender"},
                {"name": "Declan Rice",       "jersey": 4,  "row": "mid", "position": "Midfielder"},
                {"name": "Kalvin Phillips",   "jersey": 14, "row": "mid", "position": "Midfielder"},
                {"name": "Bukayo Saka",       "jersey": 17, "row": "fwd", "position": "Forward"},
                {"name": "Mason Mount",       "jersey": 19, "row": "fwd", "position": "Forward"},
                {"name": "Raheem Sterling",   "jersey": 10, "row": "fwd", "position": "Forward"},
                {"name": "Harry Kane",        "jersey": 9,  "row": "fwd", "position": "Forward"},
            ],
        },
    },
    {
        "id": "wc_final_2014",
        "competition": "FIFA World Cup Final",
        "date": "13 July 2014",
        "venue": "Maracanã, Rio de Janeiro",
        "home": {
            "name": "Germany",
            "colour_primary": "#f1f5f9",
            "colour_secondary": "#1e293b",
            "xi": [
                {"name": "Manuel Neuer",          "jersey": 1,  "row": "gk",  "position": "Goalkeeper"},
                {"name": "Philipp Lahm",           "jersey": 16, "row": "def", "position": "Defender"},
                {"name": "Jérôme Boateng",        "guess_name": "Boateng",    "jersey": 17, "row": "def", "position": "Defender"},
                {"name": "Mats Hummels",           "jersey": 5,  "row": "def", "position": "Defender"},
                {"name": "Benedikt Höwedes",      "guess_name": "Howedes",    "jersey": 4,  "row": "def", "position": "Defender"},
                {"name": "Bastian Schweinsteiger", "jersey": 7,  "row": "mid", "position": "Midfielder"},
                {"name": "Sami Khedira",           "jersey": 6,  "row": "mid", "position": "Midfielder"},
                {"name": "Thomas Müller",         "guess_name": "Muller",     "jersey": 13, "row": "mid", "position": "Midfielder"},
                {"name": "Toni Kroos",             "jersey": 18, "row": "mid", "position": "Midfielder"},
                {"name": "Mesut Özil",            "guess_name": "Ozil",       "jersey": 8,  "row": "mid", "position": "Midfielder"},
                {"name": "Miroslav Klose",         "jersey": 11, "row": "fwd", "position": "Forward"},
            ],
        },
        "away": {
            "name": "Argentina",
            "colour_primary": "#60a5fa",
            "colour_secondary": "#f1f5f9",
            "xi": [
                {"name": "Sergio Romero",          "jersey": 1,  "row": "gk",  "position": "Goalkeeper"},
                {"name": "Pablo Zabaleta",         "jersey": 2,  "row": "def", "position": "Defender"},
                {"name": "Martin Demichelis",      "jersey": 6,  "row": "def", "position": "Defender"},
                {"name": "Ezequiel Garay",         "jersey": 3,  "row": "def", "position": "Defender"},
                {"name": "Marcos Rojo",            "jersey": 16, "row": "def", "position": "Defender"},
                {"name": "Javier Mascherano",      "jersey": 14, "row": "mid", "position": "Midfielder"},
                {"name": "Enzo Pérez",             "guess_name": "Perez",      "jersey": 13, "row": "mid", "position": "Midfielder"},
                {"name": "Ángel Di María",         "guess_name": "Di Maria",   "jersey": 7,  "row": "mid", "position": "Midfielder"},
                {"name": "Lionel Messi",           "jersey": 10, "row": "fwd", "position": "Forward"},
                {"name": "Gonzalo Higuaín",        "guess_name": "Higuain",    "jersey": 9,  "row": "fwd", "position": "Forward"},
                {"name": "Ezequiel Lavezzi",       "jersey": 22, "row": "fwd", "position": "Forward"},
            ],
        },
    },
    {
        "id": "cl_final_2012",
        "competition": "UEFA Champions League Final",
        "date": "19 May 2012",
        "venue": "Allianz Arena, Munich",
        "home": {
            "name": "Chelsea FC",
            "colour_primary": "#2563eb",
            "colour_secondary": "#1e3a8a",
            "xi": [
                {"name": "Petr Čech",         "guess_name": "Cech",       "jersey": 1,  "row": "gk",  "position": "Goalkeeper"},
                {"name": "José Bosingwa",     "guess_name": "Bosingwa",   "jersey": 2,  "row": "def", "position": "Defender"},
                {"name": "Gary Cahill",        "jersey": 24, "row": "def", "position": "Defender"},
                {"name": "John Terry",         "jersey": 26, "row": "def", "position": "Defender"},
                {"name": "Ashley Cole",        "jersey": 3,  "row": "def", "position": "Defender"},
                {"name": "Ramires",            "jersey": 7,  "row": "mid", "position": "Midfielder"},
                {"name": "John Obi Mikel",    "guess_name": "Mikel",      "jersey": 12, "row": "mid", "position": "Midfielder"},
                {"name": "Frank Lampard",      "jersey": 8,  "row": "mid", "position": "Midfielder"},
                {"name": "Juan Mata",          "jersey": 10, "row": "fwd", "position": "Forward"},
                {"name": "Salomon Kalou",     "guess_name": "Kalou",      "jersey": 21, "row": "fwd", "position": "Forward"},
                {"name": "Didier Drogba",      "jersey": 11, "row": "fwd", "position": "Forward"},
            ],
        },
        "away": {
            "name": "FC Bayern München",
            "colour_primary": "#dc2626",
            "colour_secondary": "#991b1b",
            "xi": [
                {"name": "Manuel Neuer",           "jersey": 1,  "row": "gk",  "position": "Goalkeeper"},
                {"name": "Philipp Lahm",            "jersey": 21, "row": "def", "position": "Defender"},
                {"name": "Jérôme Boateng",         "guess_name": "Boateng",      "jersey": 17, "row": "def", "position": "Defender"},
                {"name": "Holger Badstuber",        "jersey": 28, "row": "def", "position": "Defender"},
                {"name": "David Alaba",             "jersey": 27, "row": "def", "position": "Defender"},
                {"name": "Bastian Schweinsteiger",  "jersey": 31, "row": "mid", "position": "Midfielder"},
                {"name": "Toni Kroos",              "jersey": 39, "row": "mid", "position": "Midfielder"},
                {"name": "Arjen Robben",            "jersey": 10, "row": "fwd", "position": "Forward"},
                {"name": "Thomas Müller",          "guess_name": "Muller",       "jersey": 25, "row": "fwd", "position": "Forward"},
                {"name": "Franck Ribéry",          "guess_name": "Ribery",       "jersey": 7,  "row": "fwd", "position": "Forward"},
                {"name": "Mario Gómez",            "guess_name": "Gomez",        "jersey": 33, "row": "fwd", "position": "Forward"},
            ],
        },
    },
    {
        "id": "wc_final_2010",
        "competition": "FIFA World Cup Final",
        "date": "11 July 2010",
        "venue": "Soccer City, Johannesburg",
        "home": {
            "name": "Spain",
            "colour_primary": "#dc2626",
            "colour_secondary": "#fbbf24",
            "xi": [
                {"name": "Iker Casillas",         "jersey": 1,  "row": "gk",  "position": "Goalkeeper"},
                {"name": "Sergio Ramos",           "jersey": 15, "row": "def", "position": "Defender"},
                {"name": "Gerard Piqué",          "guess_name": "Pique",      "jersey": 3,  "row": "def", "position": "Defender"},
                {"name": "Carles Puyol",           "jersey": 5,  "row": "def", "position": "Defender"},
                {"name": "Joan Capdevila",         "jersey": 11, "row": "def", "position": "Defender"},
                {"name": "Xabi Alonso",            "jersey": 14, "row": "mid", "position": "Midfielder"},
                {"name": "Sergio Busquets",        "jersey": 16, "row": "mid", "position": "Midfielder"},
                {"name": "Xavi",                   "jersey": 8,  "row": "mid", "position": "Midfielder"},
                {"name": "Andrés Iniesta",        "guess_name": "Iniesta",    "jersey": 6,  "row": "mid", "position": "Midfielder"},
                {"name": "Fernando Torres",        "jersey": 9,  "row": "fwd", "position": "Forward"},
                {"name": "David Villa",            "jersey": 7,  "row": "fwd", "position": "Forward"},
            ],
        },
        "away": {
            "name": "Netherlands",
            "colour_primary": "#f97316",
            "colour_secondary": "#ea580c",
            "xi": [
                {"name": "Maarten Stekelenburg",    "guess_name": "Stekelenburg", "jersey": 1,  "row": "gk",  "position": "Goalkeeper"},
                {"name": "Gregory van der Wiel",    "guess_name": "Van der Wiel", "jersey": 2,  "row": "def", "position": "Defender"},
                {"name": "John Heitinga",            "jersey": 3,  "row": "def", "position": "Defender"},
                {"name": "Joris Mathijsen",          "jersey": 4,  "row": "def", "position": "Defender"},
                {"name": "Giovanni van Bronckhorst", "guess_name": "Van Bronckhorst", "jersey": 5, "row": "def", "position": "Defender"},
                {"name": "Mark van Bommel",          "guess_name": "Van Bommel",  "jersey": 8,  "row": "mid", "position": "Midfielder"},
                {"name": "Nigel de Jong",            "guess_name": "De Jong",     "jersey": 6,  "row": "mid", "position": "Midfielder"},
                {"name": "Wesley Sneijder",          "jersey": 10, "row": "mid", "position": "Midfielder"},
                {"name": "Arjen Robben",             "jersey": 11, "row": "fwd", "position": "Forward"},
                {"name": "Dirk Kuyt",               "jersey": 9,  "row": "fwd", "position": "Forward"},
                {"name": "Robin van Persie",         "guess_name": "Van Persie",  "jersey": 7,  "row": "fwd", "position": "Forward"},
            ],
        },
    },
    {
        "id": "cl_final_2013",
        "competition": "UEFA Champions League Final",
        "date": "25 May 2013",
        "venue": "Wembley Stadium, London",
        "home": {
            "name": "FC Bayern München",
            "colour_primary": "#dc2626",
            "colour_secondary": "#991b1b",
            "xi": [
                {"name": "Manuel Neuer",           "jersey": 1,  "row": "gk",  "position": "Goalkeeper"},
                {"name": "Philipp Lahm",            "jersey": 21, "row": "def", "position": "Defender"},
                {"name": "Jérôme Boateng",         "guess_name": "Boateng",  "jersey": 17, "row": "def", "position": "Defender"},
                {"name": "Dante",                   "jersey": 4,  "row": "def", "position": "Defender"},
                {"name": "David Alaba",             "jersey": 27, "row": "def", "position": "Defender"},
                {"name": "Bastian Schweinsteiger",  "jersey": 31, "row": "mid", "position": "Midfielder"},
                {"name": "Javi Martínez",          "guess_name": "Martinez", "jersey": 8,  "row": "mid", "position": "Midfielder"},
                {"name": "Arjen Robben",            "jersey": 10, "row": "fwd", "position": "Forward"},
                {"name": "Thomas Müller",          "guess_name": "Muller",   "jersey": 25, "row": "fwd", "position": "Forward"},
                {"name": "Franck Ribéry",          "guess_name": "Ribery",   "jersey": 7,  "row": "fwd", "position": "Forward"},
                {"name": "Mario Mandžukić",        "guess_name": "Mandzukic","jersey": 9,  "row": "fwd", "position": "Forward"},
            ],
        },
        "away": {
            "name": "Borussia Dortmund",
            "colour_primary": "#eab308",
            "colour_secondary": "#78350f",
            "xi": [
                {"name": "Roman Weidenfeller",  "jersey": 1,  "row": "gk",  "position": "Goalkeeper"},
                {"name": "Łukasz Piszczek",    "guess_name": "Piszczek",  "jersey": 26, "row": "def", "position": "Defender"},
                {"name": "Neven Subotić",      "guess_name": "Subotic",   "jersey": 4,  "row": "def", "position": "Defender"},
                {"name": "Mats Hummels",        "jersey": 15, "row": "def", "position": "Defender"},
                {"name": "Marcel Schmelzer",    "jersey": 29, "row": "def", "position": "Defender"},
                {"name": "Sven Bender",         "jersey": 6,  "row": "mid", "position": "Midfielder"},
                {"name": "İlkay Gündoğan",     "guess_name": "Gundogan", "jersey": 8,  "row": "mid", "position": "Midfielder"},
                {"name": "Jakub Błaszczykowski","guess_name": "Blaszczykowski","jersey":16,"row":"fwd","position":"Forward"},
                {"name": "Mario Götze",        "guess_name": "Gotze",     "jersey": 10, "row": "fwd", "position": "Forward"},
                {"name": "Kevin Grosskreutz",   "jersey": 19, "row": "fwd", "position": "Forward"},
                {"name": "Robert Lewandowski",  "jersey": 9,  "row": "fwd", "position": "Forward"},
            ],
        },
    },
    {
        "id": "cl_final_2008",
        "competition": "UEFA Champions League Final",
        "date": "21 May 2008",
        "venue": "Luzhniki Stadium, Moscow",
        "home": {
            "name": "Manchester United",
            "colour_primary": "#dc2626",
            "colour_secondary": "#7f1d1d",
            "xi": [
                {"name": "Edwin van der Sar",    "guess_name": "Van der Sar", "jersey": 1,  "row": "gk",  "position": "Goalkeeper"},
                {"name": "Wes Brown",             "jersey": 6,  "row": "def", "position": "Defender"},
                {"name": "Rio Ferdinand",         "jersey": 5,  "row": "def", "position": "Defender"},
                {"name": "Nemanja Vidić",        "guess_name": "Vidic",      "jersey": 15, "row": "def", "position": "Defender"},
                {"name": "Patrice Evra",          "jersey": 3,  "row": "def", "position": "Defender"},
                {"name": "Owen Hargreaves",       "jersey": 4,  "row": "mid", "position": "Midfielder"},
                {"name": "Michael Carrick",       "jersey": 16, "row": "mid", "position": "Midfielder"},
                {"name": "Paul Scholes",          "jersey": 18, "row": "mid", "position": "Midfielder"},
                {"name": "Wayne Rooney",          "jersey": 8,  "row": "fwd", "position": "Forward"},
                {"name": "Carlos Tevez",          "jersey": 32, "row": "fwd", "position": "Forward"},
                {"name": "Cristiano Ronaldo",     "jersey": 7,  "row": "fwd", "position": "Forward"},
            ],
        },
        "away": {
            "name": "Chelsea FC",
            "colour_primary": "#2563eb",
            "colour_secondary": "#1e3a8a",
            "xi": [
                {"name": "Petr Čech",       "guess_name": "Cech",     "jersey": 1,  "row": "gk",  "position": "Goalkeeper"},
                {"name": "Michael Essien",   "jersey": 5,  "row": "def", "position": "Defender"},
                {"name": "Ricardo Carvalho", "jersey": 6,  "row": "def", "position": "Defender"},
                {"name": "John Terry",       "jersey": 26, "row": "def", "position": "Defender"},
                {"name": "Ashley Cole",      "jersey": 3,  "row": "def", "position": "Defender"},
                {"name": "Claude Makélélé", "guess_name": "Makelele", "jersey": 4,  "row": "mid", "position": "Midfielder"},
                {"name": "Michael Ballack",  "jersey": 13, "row": "mid", "position": "Midfielder"},
                {"name": "Frank Lampard",    "jersey": 8,  "row": "mid", "position": "Midfielder"},
                {"name": "Salomon Kalou",   "guess_name": "Kalou",    "jersey": 21, "row": "fwd", "position": "Forward"},
                {"name": "Didier Drogba",    "jersey": 11, "row": "fwd", "position": "Forward"},
                {"name": "Joe Cole",         "jersey": 10, "row": "fwd", "position": "Forward"},
            ],
        },
    },
    {
        "id": "cl_final_2016",
        "competition": "UEFA Champions League Final",
        "date": "28 May 2016",
        "venue": "San Siro, Milan",
        "home": {
            "name": "Real Madrid",
            "colour_primary": "#f1f5f9",
            "colour_secondary": "#475569",
            "xi": [
                {"name": "Keylor Navas",     "jersey": 1,  "row": "gk",  "position": "Goalkeeper"},
                {"name": "Dani Carvajal",    "jersey": 2,  "row": "def", "position": "Defender"},
                {"name": "Pepe",             "jersey": 3,  "row": "def", "position": "Defender"},
                {"name": "Sergio Ramos",     "jersey": 4,  "row": "def", "position": "Defender"},
                {"name": "Marcelo",          "jersey": 12, "row": "def", "position": "Defender"},
                {"name": "Casemiro",         "jersey": 14, "row": "mid", "position": "Midfielder"},
                {"name": "Luka Modrić",      "guess_name": "Modric",    "jersey": 10, "row": "mid", "position": "Midfielder"},
                {"name": "Toni Kroos",       "jersey": 8,  "row": "mid", "position": "Midfielder"},
                {"name": "Gareth Bale",      "jersey": 11, "row": "fwd", "position": "Forward"},
                {"name": "Karim Benzema",    "jersey": 9,  "row": "fwd", "position": "Forward"},
                {"name": "Cristiano Ronaldo","jersey": 7,  "row": "fwd", "position": "Forward"},
            ],
        },
        "away": {
            "name": "Atlético de Madrid",
            "colour_primary": "#dc2626",
            "colour_secondary": "#1e3a8a",
            "xi": [
                {"name": "Jan Oblak",              "jersey": 13, "row": "gk",  "position": "Goalkeeper"},
                {"name": "Juanfran",               "jersey": 2,  "row": "def", "position": "Defender"},
                {"name": "Diego Godín",  "guess_name": "Godin",  "jersey": 2,  "row": "def", "position": "Defender"},
                {"name": "Stefan Savić", "guess_name": "Savic",  "jersey": 15, "row": "def", "position": "Defender"},
                {"name": "Filipe Luís", "guess_name": "Filipe Luis", "jersey": 3, "row": "def", "position": "Defender"},
                {"name": "Gabi",                   "jersey": 14, "row": "mid", "position": "Midfielder"},
                {"name": "Koke",                   "jersey": 6,  "row": "mid", "position": "Midfielder"},
                {"name": "Saúl Ñíguez",           "guess_name": "Saul",       "jersey": 8,  "row": "mid", "position": "Midfielder"},
                {"name": "Yannick Carrasco",       "jersey": 11, "row": "fwd", "position": "Forward"},
                {"name": "Antoine Griezmann",      "jersey": 7,  "row": "fwd", "position": "Forward"},
                {"name": "Fernando Torres",        "jersey": 9,  "row": "fwd", "position": "Forward"},
            ],
        },
    },
    {
        "id": "cl_final_2017",
        "competition": "UEFA Champions League Final",
        "date": "3 June 2017",
        "venue": "National Stadium of Wales, Cardiff",
        "home": {
            "name": "Real Madrid",
            "colour_primary": "#f1f5f9",
            "colour_secondary": "#475569",
            "xi": [
                {"name": "Keylor Navas",    "jersey": 1,  "row": "gk",  "position": "Goalkeeper"},
                {"name": "Dani Carvajal",   "jersey": 2,  "row": "def", "position": "Defender"},
                {"name": "Raphaël Varane",  "guess_name": "Varane",   "jersey": 5,  "row": "def", "position": "Defender"},
                {"name": "Sergio Ramos",    "jersey": 4,  "row": "def", "position": "Defender"},
                {"name": "Marcelo",         "jersey": 12, "row": "def", "position": "Defender"},
                {"name": "Casemiro",        "jersey": 14, "row": "mid", "position": "Midfielder"},
                {"name": "Luka Modrić",     "guess_name": "Modric",   "jersey": 10, "row": "mid", "position": "Midfielder"},
                {"name": "Toni Kroos",      "jersey": 8,  "row": "mid", "position": "Midfielder"},
                {"name": "Isco",            "jersey": 22, "row": "fwd", "position": "Forward"},
                {"name": "Karim Benzema",   "jersey": 9,  "row": "fwd", "position": "Forward"},
                {"name": "Cristiano Ronaldo","jersey": 7,  "row": "fwd", "position": "Forward"},
            ],
        },
        "away": {
            "name": "Juventus FC",
            "colour_primary": "#1e293b",
            "colour_secondary": "#334155",
            "xi": [
                {"name": "Gianluigi Buffon",   "jersey": 1,  "row": "gk",  "position": "Goalkeeper"},
                {"name": "Dani Alves",         "jersey": 23, "row": "def", "position": "Defender"},
                {"name": "Leonardo Bonucci",   "jersey": 19, "row": "def", "position": "Defender"},
                {"name": "Giorgio Chiellini",  "jersey": 3,  "row": "def", "position": "Defender"},
                {"name": "Alex Sandro",        "jersey": 12, "row": "def", "position": "Defender"},
                {"name": "Miralem Pjanić",    "guess_name": "Pjanic",   "jersey": 5,  "row": "mid", "position": "Midfielder"},
                {"name": "Sami Khedira",       "jersey": 6,  "row": "mid", "position": "Midfielder"},
                {"name": "Juan Cuadrado",      "jersey": 7,  "row": "mid", "position": "Midfielder"},
                {"name": "Paulo Dybala",       "jersey": 10, "row": "fwd", "position": "Forward"},
                {"name": "Mario Mandžukić",   "guess_name": "Mandzukic","jersey": 17, "row": "fwd", "position": "Forward"},
                {"name": "Gonzalo Higuaín",   "guess_name": "Higuain",  "jersey": 9,  "row": "fwd", "position": "Forward"},
            ],
        },
    },
    {
        "id": "cl_final_2018",
        "competition": "UEFA Champions League Final",
        "date": "26 May 2018",
        "venue": "NSC Olimpiyskiy, Kyiv",
        "home": {
            "name": "Real Madrid",
            "colour_primary": "#f1f5f9",
            "colour_secondary": "#475569",
            "xi": [
                {"name": "Keylor Navas",     "jersey": 1,  "row": "gk",  "position": "Goalkeeper"},
                {"name": "Dani Carvajal",    "jersey": 2,  "row": "def", "position": "Defender"},
                {"name": "Raphaël Varane",   "guess_name": "Varane",   "jersey": 5,  "row": "def", "position": "Defender"},
                {"name": "Sergio Ramos",     "jersey": 4,  "row": "def", "position": "Defender"},
                {"name": "Marcelo",          "jersey": 12, "row": "def", "position": "Defender"},
                {"name": "Casemiro",         "jersey": 14, "row": "mid", "position": "Midfielder"},
                {"name": "Luka Modrić",      "guess_name": "Modric",   "jersey": 10, "row": "mid", "position": "Midfielder"},
                {"name": "Toni Kroos",       "jersey": 8,  "row": "mid", "position": "Midfielder"},
                {"name": "Isco",             "jersey": 22, "row": "fwd", "position": "Forward"},
                {"name": "Karim Benzema",    "jersey": 9,  "row": "fwd", "position": "Forward"},
                {"name": "Cristiano Ronaldo","jersey": 7,  "row": "fwd", "position": "Forward"},
            ],
        },
        "away": {
            "name": "Liverpool FC",
            "colour_primary": "#dc2626",
            "colour_secondary": "#7f1d1d",
            "xi": [
                {"name": "Loris Karius",            "jersey": 1,  "row": "gk",  "position": "Goalkeeper"},
                {"name": "Trent Alexander-Arnold",  "guess_name": "Arnold",     "jersey": 66, "row": "def", "position": "Defender"},
                {"name": "Dejan Lovren",            "jersey": 6,  "row": "def", "position": "Defender"},
                {"name": "Virgil van Dijk",         "guess_name": "Van Dijk",   "jersey": 4,  "row": "def", "position": "Defender"},
                {"name": "Andy Robertson",          "jersey": 26, "row": "def", "position": "Defender"},
                {"name": "Jordan Henderson",        "jersey": 14, "row": "mid", "position": "Midfielder"},
                {"name": "James Milner",            "jersey": 7,  "row": "mid", "position": "Midfielder"},
                {"name": "Georginio Wijnaldum",     "jersey": 5,  "row": "mid", "position": "Midfielder"},
                {"name": "Mohamed Salah",           "jersey": 11, "row": "fwd", "position": "Forward"},
                {"name": "Roberto Firmino",         "jersey": 9,  "row": "fwd", "position": "Forward"},
                {"name": "Sadio Mané",              "jersey": 19, "row": "fwd", "position": "Forward"},
            ],
        },
    },
    {
        "id": "cl_final_2011",
        "competition": "UEFA Champions League Final",
        "date": "28 May 2011",
        "venue": "Wembley Stadium, London",
        "home": {
            "name": "FC Barcelona",
            "colour_primary": "#1d4ed8",
            "colour_secondary": "#7f1d1d",
            "xi": [
                {"name": "Víctor Valdés",    "guess_name": "Valdes",   "jersey": 1,  "row": "gk",  "position": "Goalkeeper"},
                {"name": "Dani Alves",       "jersey": 22, "row": "def", "position": "Defender"},
                {"name": "Gerard Piqué",    "guess_name": "Pique",    "jersey": 3,  "row": "def", "position": "Defender"},
                {"name": "Eric Abidal",      "jersey": 22, "row": "def", "position": "Defender"},
                {"name": "Adriano",          "jersey": 21, "row": "def", "position": "Defender"},
                {"name": "Sergio Busquets",  "jersey": 16, "row": "mid", "position": "Midfielder"},
                {"name": "Xavi",             "jersey": 6,  "row": "mid", "position": "Midfielder"},
                {"name": "Andrés Iniesta",  "guess_name": "Iniesta",  "jersey": 8,  "row": "mid", "position": "Midfielder"},
                {"name": "Pedro",            "jersey": 17, "row": "fwd", "position": "Forward"},
                {"name": "Lionel Messi",     "jersey": 10, "row": "fwd", "position": "Forward"},
                {"name": "David Villa",      "jersey": 7,  "row": "fwd", "position": "Forward"},
            ],
        },
        "away": {
            "name": "Manchester United",
            "colour_primary": "#dc2626",
            "colour_secondary": "#7f1d1d",
            "xi": [
                {"name": "Edwin van der Sar",    "guess_name": "Van der Sar", "jersey": 1,  "row": "gk",  "position": "Goalkeeper"},
                {"name": "Fabio",                "jersey": 20, "row": "def", "position": "Defender"},
                {"name": "Rio Ferdinand",        "jersey": 5,  "row": "def", "position": "Defender"},
                {"name": "Nemanja Vidić",       "guess_name": "Vidic",      "jersey": 15, "row": "def", "position": "Defender"},
                {"name": "Patrice Evra",         "jersey": 3,  "row": "def", "position": "Defender"},
                {"name": "Antonio Valencia",     "guess_name": "Valencia",   "jersey": 25, "row": "mid", "position": "Midfielder"},
                {"name": "Michael Carrick",      "jersey": 16, "row": "mid", "position": "Midfielder"},
                {"name": "Park Ji-sung",         "guess_name": "Park",       "jersey": 13, "row": "mid", "position": "Midfielder"},
                {"name": "Ryan Giggs",           "jersey": 11, "row": "mid", "position": "Midfielder"},
                {"name": "Wayne Rooney",         "jersey": 10, "row": "fwd", "position": "Forward"},
                {"name": "Javier Hernández",    "guess_name": "Hernandez",  "jersey": 14, "row": "fwd", "position": "Forward"},
            ],
        },
    },
    {
        "id": "wc_final_2022",
        "competition": "FIFA World Cup Final",
        "date": "18 December 2022",
        "venue": "Lusail Stadium, Qatar",
        "home": {
            "name": "Argentina",
            "colour_primary": "#60a5fa",
            "colour_secondary": "#f1f5f9",
            "xi": [
                {"name": "Emiliano Martínez", "guess_name": "Martinez",    "jersey": 23, "row": "gk",  "position": "Goalkeeper"},
                {"name": "Nahuel Molina",      "jersey": 26, "row": "def", "position": "Defender"},
                {"name": "Cristian Romero",    "jersey": 13, "row": "def", "position": "Defender"},
                {"name": "Nicolás Otamendi",  "guess_name": "Otamendi",   "jersey": 19, "row": "def", "position": "Defender"},
                {"name": "Marcos Acuña",      "guess_name": "Acuna",      "jersey": 8,  "row": "def", "position": "Defender"},
                {"name": "Rodrigo De Paul",    "guess_name": "De Paul",    "jersey": 7,  "row": "mid", "position": "Midfielder"},
                {"name": "Enzo Fernández",    "guess_name": "Fernandez",  "jersey": 24, "row": "mid", "position": "Midfielder"},
                {"name": "Alexis Mac Allister","guess_name": "Mac Allister","jersey": 20,"row": "mid", "position": "Midfielder"},
                {"name": "Ángel Di María",    "guess_name": "Di Maria",   "jersey": 11, "row": "fwd", "position": "Forward"},
                {"name": "Lionel Messi",       "jersey": 10, "row": "fwd", "position": "Forward"},
                {"name": "Julián Álvarez",    "guess_name": "Alvarez",    "jersey": 9,  "row": "fwd", "position": "Forward"},
            ],
        },
        "away": {
            "name": "France",
            "colour_primary": "#1d4ed8",
            "colour_secondary": "#dc2626",
            "xi": [
                {"name": "Hugo Lloris",          "jersey": 1,  "row": "gk",  "position": "Goalkeeper"},
                {"name": "Jules Koundé",        "guess_name": "Kounde",     "jersey": 5,  "row": "def", "position": "Defender"},
                {"name": "Raphaël Varane",      "guess_name": "Varane",     "jersey": 4,  "row": "def", "position": "Defender"},
                {"name": "Dayot Upamecano",      "jersey": 2,  "row": "def", "position": "Defender"},
                {"name": "Théo Hernández",      "guess_name": "Hernandez",  "jersey": 22, "row": "def", "position": "Defender"},
                {"name": "Aurélien Tchouaméni", "guess_name": "Tchouameni", "jersey": 8,  "row": "mid", "position": "Midfielder"},
                {"name": "Adrien Rabiot",        "jersey": 14, "row": "mid", "position": "Midfielder"},
                {"name": "Ousmane Dembélé",     "guess_name": "Dembele",    "jersey": 11, "row": "fwd", "position": "Forward"},
                {"name": "Antoine Griezmann",    "jersey": 7,  "row": "fwd", "position": "Forward"},
                {"name": "Kylian Mbappé",       "guess_name": "Mbappe",     "jersey": 10, "row": "fwd", "position": "Forward"},
                {"name": "Olivier Giroud",       "jersey": 9,  "row": "fwd", "position": "Forward"},
            ],
        },
    },
    {
        "id": "cl_final_2005",
        "competition": "UEFA Champions League Final",
        "date": "25 May 2005",
        "venue": "Atatürk Olympic Stadium, Istanbul",
        "home": {
            "name": "Liverpool FC",
            "colour_primary": "#dc2626",
            "colour_secondary": "#7f1d1d",
            "xi": [
                {"name": "Jerzy Dudek",       "jersey": 1,  "row": "gk",  "position": "Goalkeeper"},
                {"name": "Steve Finnan",      "jersey": 3,  "row": "def", "position": "Defender"},
                {"name": "Sami Hyypiä",      "guess_name": "Hyypia",  "jersey": 4,  "row": "def", "position": "Defender"},
                {"name": "Jamie Carragher",   "jersey": 23, "row": "def", "position": "Defender"},
                {"name": "Djimi Traoré",     "guess_name": "Traore",  "jersey": 22, "row": "def", "position": "Defender"},
                {"name": "Luis García",      "guess_name": "Garcia",  "jersey": 10, "row": "mid", "position": "Midfielder"},
                {"name": "Steven Gerrard",    "jersey": 8,  "row": "mid", "position": "Midfielder"},
                {"name": "Xabi Alonso",       "jersey": 14, "row": "mid", "position": "Midfielder"},
                {"name": "John Arne Riise",   "guess_name": "Riise",   "jersey": 6,  "row": "mid", "position": "Midfielder"},
                {"name": "Harry Kewell",      "jersey": 7,  "row": "fwd", "position": "Forward"},
                {"name": "Milan Baroš",      "guess_name": "Baros",   "jersey": 5,  "row": "fwd", "position": "Forward"},
            ],
        },
        "away": {
            "name": "AC Milan",
            "colour_primary": "#dc2626",
            "colour_secondary": "#1e1e2e",
            "xi": [
                {"name": "Dida",              "jersey": 1,  "row": "gk",  "position": "Goalkeeper"},
                {"name": "Cafu",              "jersey": 2,  "row": "def", "position": "Defender"},
                {"name": "Alessandro Nesta",  "guess_name": "Nesta",     "jersey": 13, "row": "def", "position": "Defender"},
                {"name": "Jaap Stam",         "jersey": 5,  "row": "def", "position": "Defender"},
                {"name": "Paolo Maldini",     "jersey": 3,  "row": "def", "position": "Defender"},
                {"name": "Gennaro Gattuso",   "guess_name": "Gattuso",   "jersey": 8,  "row": "mid", "position": "Midfielder"},
                {"name": "Andrea Pirlo",      "jersey": 21, "row": "mid", "position": "Midfielder"},
                {"name": "Clarence Seedorf",  "jersey": 10, "row": "mid", "position": "Midfielder"},
                {"name": "Kaká",             "guess_name": "Kaka",      "jersey": 22, "row": "fwd", "position": "Forward"},
                {"name": "Hernán Crespo",    "guess_name": "Crespo",    "jersey": 7,  "row": "fwd", "position": "Forward"},
                {"name": "Andriy Shevchenko","guess_name": "Shevchenko","jersey": 76, "row": "fwd", "position": "Forward"},
            ],
        },
    },
]


def get_random_match() -> dict:
    return _random.choice(FAMOUS_MATCHES)
